# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'


##### Terminal behavior #####

set -as terminal-features ",xterm-256color:RGB"

set -g set-clipboard external

##### General behavior #####

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g status-keys vi

##### Keybinds #####

# TODO ideally we have binds which let us jump directly to window
# Vim navigation
bind -n M-H previous-window
bind -n M-L next-window

# Configure prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Tmux yank
# Enter vim mode with prefix [
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Split with current working directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Layouts
bind Space next-layout
bind = select-layout tiled

# Toggle fullscreen
bind z resize-pane -Z  ##### Persistent pane mode #####

bind p switch-client -T pane-mode

bind -T pane-mode h select-pane -L \; switch-client -T pane-mode
bind -T pane-mode j select-pane -D \; switch-client -T pane-mode
bind -T pane-mode k select-pane -U \; switch-client -T pane-mode
bind -T pane-mode l select-pane -R \; switch-client -T pane-mode

bind -T pane-mode H resize-pane -L 3 \; switch-client -T pane-mode
bind -T pane-mode J resize-pane -D 3 \; switch-client -T pane-mode
bind -T pane-mode K resize-pane -U 3 \; switch-client -T pane-mode
bind -T pane-mode L resize-pane -R 3 \; switch-client -T pane-mode

bind -T pane-mode | split-window -h -c "#{pane_current_path}" \; switch-client -T pane-mode
bind -T pane-mode - split-window -v -c "#{pane_current_path}" \; switch-client -T pane-mode

bind -T pane-mode z resize-pane -Z \; switch-client -T pane-mode
bind -T pane-mode = select-layout tiled \; switch-client -T pane-mode
bind -T pane-mode Space next-layout \; switch-client -T pane-mode

bind -T pane-mode > swap-pane -D \; switch-client -T pane-mode
bind -T pane-mode < swap-pane -U \; switch-client -T pane-mode

bind -T pane-mode x confirm-before -p "Kill pane? (y/n)" \
    "kill-pane; switch-client -T pane-mode"
set -g status-left-length 40
set -g status-left \
    '#{?#{==:#{client_key_table},pane-mode},#[bg=yellow#,fg=black#,bold] PANE MODE #[default] ,} #S '

bind -T pane-mode q switch-client -T root
bind -T pane-mode Escape switch-client -T root

# TODO indicate we are in pane mode

##### Window Naming #####
# rename with prefix ,

# prevent tmux rename
set -g automatic-rename off
set -g allow-rename off

##### Pane Naming #####
bind T command-prompt -p "Pane name:" \
    "set-option -p @pane_name '%%'"

set -g pane-border-status top
set -g pane-border-format \
    ' #{pane_index}: #{?@pane_name,#{@pane_name},#{pane_current_command}} '

bind C command-prompt -p "Clear pane name? Press Enter" \
      "set-option -pu @pane_name"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
