# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'


##### Terminal behavior #####

set -as terminal-features ",xterm-256color:RGB"

set -g set-clipboard external

##### General behavior #####

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g status-keys vi

##### Keybinds #####

# Vim navigation
bind -n M-H previous-window
bind -n M-L next-window

# Configure prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Tmux yank
# Enter vim mode with prefix [
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Move panes
bind -r H swap-pane -U
bind -r L swap-pane -D

# Split with current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
